# Generated by Django 4.0.1 on 2022-01-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mainphoto',
        ),
    ]
